version: '0.8'
networks:
  api-connection:
    driver: bridge

services:
  workspace:
    build:
      context: ./workspace
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
        - DEFAULT_USERNAME=${DEFAULT_USERNAME}
    volumes:
      - ${LOCAL_PROJECT_PATH}/workspace:${DEFAULT_PATH}
    ports:
      - "${WORKSPACE_HOST_PORT}:80"
    tty: true

  study-coding-test:
    build:
      context: ./study-coding-test
      args:
        - PYTHON_VERSION=3.8
        - DEFAULT_USERNAME=${DEFAULT_USERNAME}
    volumes:
      - ${LOCAL_PROJECT_PATH}:${DEFAULT_PATH}
    ports:
      - "${WORKSPACE_HOST_PORT}:80"
    tty: true
  nginx:
    depends_on:
      - hani-serving-data
    build: ./nginx
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/hani-serving-data.conf:/etc/nginx/hani-serving-data.conf
    ports:
      - "80:80"
    networks:
      - api-connection

  hani-serving-data:
    container_name: hani-serving-data
    build:
      context: ./hani-serving-data
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
        - LIBGL_PATH=/usr/lib/x86_64-linux-gnu/libGL.so.1
    restart: always
    environment:
      - APP_NAME=hani-serving-data
    command: gunicorn -k uvicorn.workers.UvicornWorker main:app --bind 0.0.0.0:8000
    volumes:
      - ${LOCAL_PROJECT_PATH}:${DEFAULT_PATH}
    networks:
      - api-connection
    expose:
      - "8000"