version: '0.8'

services:
  workspace:
    build:
      context: ./workspace
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
        - DEFAULT_USERNAME=${DEFAULT_USERNAME}
    volumes:
      - ${LOCAL_PROJECT_PATH}/workspace:${DEFAULT_PATH}
    ports:
      - "${WORKSPACE_HOST_PORT}:80"
    tty: true

  study-coding-test:
    build:
      context: ./study-coding-test
      args:
        - PYTHON_VERSION=3.8
        - DEFAULT_USERNAME=${DEFAULT_USERNAME}
    volumes:
      - ${LOCAL_PROJECT_PATH}:${DEFAULT_PATH}
    ports:
      - "${WORKSPACE_HOST_PORT}:80"
    tty: true

  hani-serving-data:
    build:
      context: ./hani-serving-data
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
    container_name: hani-serving-data
    restart: always
    environment:
      - APP_NAME=hani-serving-data
    volumes:
      - ${LOCAL_PROJECT_PATH}:${DEFAULT_PATH}
    expose:
      - 9000
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
